/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Providers/theme-provider";
import { ActiveThemeProvider } from "@/components/active-theme";
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";

// 👇 1. Add these imports for the sidebar system
import {
	SidebarProvider,
	SidebarInset,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const META_THEME_COLORS = {
	white: "#ffffff",
	black: "#090909b",
};
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
	const sidebarState = cookieStore.get("sidebar:state");
	// Default to false (closed) so it doesn't pop up unexpectedly
	const defaultOpen = sidebarState ? sidebarState.value === "true" : false;

	const activeThemeValue = cookieStore.get("active_theme")?.value;
	const isScaled = activeThemeValue?.endsWith("-scaled");



	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"bg-background overscroll-none font-sans antialiased",
					activeThemeValue ? `theme-${activeThemeValue}` : "",
					isScaled ? "theme-scaled" : "",
					geistSans.variable,
					geistMono.variable,
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					enableColorScheme
				>
					<ActiveThemeProvider initialTheme={activeThemeValue}>
						{/* 👇 2. Sidebar Provider wraps the content area */}
						<SidebarProvider defaultOpen={defaultOpen}>
							{/* The Actual Sidebar Component (Left Side) */}
							<AppSidebar />

							{/* SidebarInset: This handles the "push" logic so content isn't covered */}
							<SidebarInset>
								<header className="flex h-16 shrink-0 items-center gap-2 border-b px-4 sticky top-0 bg-background/95 backdrop-blur z-10 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
									<div className="flex items-center gap-2 px-4">
										{/* The Toggle Button (Top Left) */}
										<SidebarTrigger className="-ml-1" />
										<div className="h-4 w-px bg-border mx-2" />
										<span className="font-semibold">Dashboard</span>
									</div>
								</header>
								{/* Main Page Content */}
								<main className="flex flex-1 flex-col gap-4 p-4 pt-0">
									{children}
								</main>{" "}
							</SidebarInset>
						</SidebarProvider>
					</ActiveThemeProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
